In [2]:
from importlib import reload
import sys
from pathlib import Path

src_path = (Path.cwd().parent / "src").resolve()
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

import matching
import embedder
matching = reload(matching)
embedder = reload(embedder)

from matching import compute_dictionary_pairs_and_topk, dumps_skill_columns
from matching import to_skill_list

from embedder import TextEmbedder, compute_text_pairs_and_topk

import json
import pandas as pd

processed_dir = "../data/processed"

/home/vincent/miniconda3/envs/NLP/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
resume_ranked_path = f"{processed_dir}/resume_skills_extracted.csv"
job_ranked_path = f"{processed_dir}/job_skills_extracted.csv"

resume_out = pd.read_csv(resume_ranked_path)
job_out = pd.read_csv(job_ranked_path)
print("Loaded ranked extracted files")

Loaded ranked extracted files

# BGE-SMALL

In [4]:
embedder = "BAAI/bge-small-en-v1.5"

model_pairs_df, model_topk_df = compute_text_pairs_and_topk(
    resume_df=resume_out,
    job_df=job_out,
    model_name=embedder,
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 23728.29it/s]
BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [6]:
display(model_topk_df.head())
display(model_pairs_df.head())

,resume_id,job_idx,job_title,company,semantic_similarity,final_score,rank
0,20345168,176,Sanitation Supervisor,IRCA Group,0.6321,63.21,1
1,20345168,2401,Meat Cutter - Red River Co-op at Seasons Food ...,Federated Co-operatives Limited,0.6315,63.15,2
2,20345168,705,Pharmaceutical Sales Specialist - R&I Primary ...,AstraZeneca,0.6313,63.13,3
3,20345168,1642,Sous-Chef,Westlake Wine Bar,0.6280,62.80,4
4,20345168,1662,"Research Associate, WFIRM, Organs on a Chip/Ma...",Wake Forest University School of Medicine,0.6230,62.30,5

,resume_id,job_idx,job_title,company,semantic_similarity,final_score
0,20345168,0,Registered Nurse (RN) at Aveanna,Health eCareers,0.5332,53.32
1,20345168,1,Locum | Physician Obstetrics and Gynecology,Weatherby Healthcare,0.5243,52.43
2,20345168,2,Technology Sales (Recruiting) Business Develop...,Proven Recruiting,0.5014,50.14
3,20345168,3,Travel RN Oncology 1862.00/week - 23731031EXPP...,TravelNurseSource,0.5049,50.49
4,20345168,4,Floor Supervisor Full Time - TOMMY HILFIGER - ...,Tommy Hilfiger,0.5122,51.22

# MiniLM

In [ ]:
embedder = "sentence-transformers/all-MiniLM-L6-v2"

model_pairs_df, model_topk_df = compute_text_pairs_and_topk(
    resume_df=resume_out,
    job_df=job_out,
    model_name=embedder,
)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 27466.04it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [8]:
display(model_topk_df.head())
display(model_pairs_df.head())

,resume_id,job_idx,job_title,company,semantic_similarity,final_score,rank
0,20345168,12,Configuration Management (TS/SCI with CI Poly ...,North Point Technology,0.2715,27.15,1
1,20345168,17,Sales Manager - Estate Agency,Nested,0.2715,27.15,2
2,20345168,39,Residential Counselor (Direct Care) - Medical,BAMSI,0.2715,27.15,3
3,20345168,47,National Aviation Senior Design Manager,JE Dunn Construction,0.2715,27.15,4
4,20345168,60,Lab Manager,Amtex Systems Inc.,0.2715,27.15,5

,resume_id,job_idx,job_title,company,semantic_similarity,final_score
0,20345168,0,Registered Nurse (RN) at Aveanna,Health eCareers,0.0257,2.57
1,20345168,1,Locum | Physician Obstetrics and Gynecology,Weatherby Healthcare,-0.0108,-1.08
2,20345168,2,Technology Sales (Recruiting) Business Develop...,Proven Recruiting,0.1430,14.30
3,20345168,3,Travel RN Oncology 1862.00/week - 23731031EXPP...,TravelNurseSource,-0.0040,-0.40
4,20345168,4,Floor Supervisor Full Time - TOMMY HILFIGER - ...,Tommy Hilfiger,0.0292,2.92

# MPNet

In [9]:
embedder = "sentence-transformers/all-mpnet-base-v2"

model_pairs_df, model_topk_df = compute_text_pairs_and_topk(
    resume_df=resume_out,
    job_df=job_out,
    model_name=embedder,
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5559.48it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [11]:
display(model_topk_df.head())
display(model_pairs_df.head())

,resume_id,job_idx,job_title,company,semantic_similarity,final_score,rank
0,20345168,148,captain hook 2,Lever Middleware Test Company,0.2606,26.06,1
1,20345168,432,Video Editor,CoStar Group,0.2481,24.81,2
2,20345168,1528,Customer Service Rep,FITNESS SF,0.2479,24.79,3
3,20345168,1087,Global Marketing Manager,MAKEUP BY MARIO,0.2466,24.66,4
4,20345168,1809,Volunteer: Graphic Designer - Protecting Kids ...,DEFEND,0.2462,24.62,5

,resume_id,job_idx,job_title,company,semantic_similarity,final_score
0,20345168,0,Registered Nurse (RN) at Aveanna,Health eCareers,0.0601,6.01
1,20345168,1,Locum | Physician Obstetrics and Gynecology,Weatherby Healthcare,0.0314,3.14
2,20345168,2,Technology Sales (Recruiting) Business Develop...,Proven Recruiting,0.1528,15.28
3,20345168,3,Travel RN Oncology 1862.00/week - 23731031EXPP...,TravelNurseSource,0.0801,8.01
4,20345168,4,Floor Supervisor Full Time - TOMMY HILFIGER - ...,Tommy Hilfiger,0.0248,2.48